-- MySQL Script generated by MySQL Workbench
-- Wed Jun  1 23:53:13 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema documents
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `documents` ;

-- -----------------------------------------------------
-- Schema documents
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `documents` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `documents` ;

-- -----------------------------------------------------
-- Table `sec_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sec_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sec_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `loginname` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL,
  `realname` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `pw` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `phone` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `email` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `address` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `lastlogin` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `lastlogin`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;
CREATE UNIQUE INDEX `loginname_UNIQUE` ON `sec_user` (`loginname` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
